version : '3'
services:
    postgres:
      image: postgres
      shm_size: '4gb'
      container_name: postgres
      restart: unless_stopped
      enviroment:
       - POSTGRES_HOST_AUTH_METHOD=trust
      ports:
       - 5432:5432
      volumes:
       - postgres:var/lib/postgressql/data
volumes:
    postgres:
      driver: local
